### ISSUE TITLE
ansible-core==2.21.0 : Module failed: 'JuniperJunosModule' object has no attribute 'safe_eval'

### ISSUE THREAD

**Issue by andyjsharp** [Juniper/ansible-junos-stdlib#825]
ansible-core==2.21.0

Since upgrading from Ansible-Core 2.20.5 to 2.21.0 it doesn't appear to be possible to use juniper.device 2.0.1 without hitting the following:

```text
TASK [Run storage cleanup dry-run RPC] *****************************************************************************
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: Importing 'to_bytes' from 'ansible.module_utils._text' is deprecated. This feature will be removed from ansible-core version 2.24. Use ansible.module_utils.common.text.converters instead.
[ERROR]: Task failed: Module failed: 'JuniperJunosModule' object has no attribute 'safe_eval'
Origin: /tmp/testing/project/tasks/upgrade/storage_cleanup_dryrun.yml:5:3

<snip>
fatal: [SRX-1]: FAILED! => {"changed": false, "changed_when_result": false, "msg": "Task failed: Module failed: 'JuniperJunosModule' object has no attribute 'safe_eval'"}
```

I suspect that this is because the deprecated function safe_eval has now been removed from 2.21.0

ref: module_utils - Remove previously deprecated safe_eval function (#85996) (#85999)
[https://github.com/ansible/ansible/blob/stable-2.21/changelogs/CHANGELOG-v2.21.rst#removed-features-previously-deprecated](https://github.com/ansible/ansible/blob/stable-2.21/changelogs/CHANGELOG-v2.21.rst#removed-features-previously-deprecated)

**Comment by chidanandpujar** [comment]
fixed and merged - https://github.com/Juniper/ansible-junos-stdlib/pull/838
